package net.blusalt.mposplugin.processor.processor_blusalt

enum class MposDownloadReasonCode {

    SUCCESSFUL, MANUAL_INITIAL_POS_SETUP, CONNECTION_ERROR,

    UNABLE_TO_GENERATE_KEY_PAIR, UNABLE_TO_GET_PRIVATE_KEY, UNABLE_TO_GET_PUBLIC_KEY,

    UNABLE_TO_DECRYPT_RSA_KEY, UNABLE_TO_ENCRYPT_RSA_KEY, MISSING_RSA_TMK, ZMK_KEY_CHECK_FAIL,

    TMK_KEY_CHECK_FAIL, TSK_KEY_CHECK_FAIL, TPK_KEY_CHECK_FAIL, TMK_KEY_SAVE_FAIL,

    TSK_KEY_SAVE_FAIL, TPK_KEY_SAVE_FAIL, KEY_VALUE_CHECK_FAIL, MISSING_ZMK,

    MISSING_SECURITY_MODULE_HOST, MISSING_SECURITY_MODULE_PORT,

    SECURITY_MODULE_UNABLE_TO_EXPORT_KEY_TO_RSA, BAD_KEY_ERROR, BAD_TERMINAL_PARAMETERS,

    BAD_CAPK_ERROR, BAD_AID_ERROR, DOWNLOAD_FAILED, KEY_OPERATION_FAIL, KEY_SAVE_FAIL,

    CTMK_RSA_DECRYPT_FAIL, UNKNOWN_DOWNLOAD_OPERATION, INITIAL_SET_UP_FAILED,

    TMK_SET_UP_FAILED, TSK_SET_UP_FAILED, TPK_SET_UP_FAILED, POS_CONFIG_PARAMS_SET_UP_FAILED,

    CAPK_SET_UP_FAILED, AID_SET_UP_FAILED, UNKNOWN_ERROR
}
